# This is a sandbox

In [2]:
# imports section
import numpy as np
import math
from numpy import dot
from numpy.linalg import norm
from gensim import corpora, models, similarities
import string

In [ ]:
text = "text text text Valentyn hello"

In [3]:
def tokenize(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))

    # ADD MORE PROCESSING

    corpus = text.split(' ')
    return corpus

In [19]:
def tfidf_example(texts):
    corpuses = [tokenize(text) for text in texts]

    vocab = sorted(set(sum(corpuses, [])))
    vocab_dict = {k:i for i,k in enumerate(vocab)}

    X_tf = np.zeros((len(corpuses), len(vocab)), dtype=int)

    for i, doc in enumerate(corpuses):
        for word in doc:
            X_tf[i, vocab_dict[word]] += 1

    print(X_tf.astype(bool).sum(axis=0))
    idf = np.log(X_tf.shape[0]/X_tf.astype(bool).sum(axis=0))
    X_tfidf = X_tf * idf

    X_tfidf_norm = X_tfidf / np.linalg.norm(X_tfidf, axis=1)[:,None]
    M = X_tfidf_norm @ X_tfidf_norm.T
    print(M)

    return 

texts = ["text text text Valentyn hello", "hello hello", "Valentyn Nastya hello", "test qwerty", "test qwerty"]
tfidf_example(texts)

{'hello': 0, 'nastya': 1, 'qwerty': 2, 'test': 3, 'text': 4, 'valentyn': 5}
[[1 0 0 0 3 1]
 [2 0 0 0 0 0]
 [1 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]]
[3 1 2 2 1 2]
[[1.         0.10338578 0.11593887 0.         0.        ]
 [0.10338578 1.         0.26589559 0.         0.        ]
 [0.11593887 0.26589559 1.         0.         0.        ]
 [0.         0.         0.         1.         1.        ]
 [0.         0.         0.         1.         1.        ]]


1. word2vec
2. datasets parsing
3. ml algorithms 
4. ml + fl 
5. 