In [2]:
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
from skfuzzy import control as ctrl
import pandas as pd

# Automated rule generation

The basic idea here is to introduce the automated rule generation for fuzzy logic ruleset.

In [36]:
moods = ["Angry", "Worried", "Sad", "Calm", "Happy", "Excited"]

df = pd.read_csv('../sets/ruleset_train.csv')
ruleset = df.loc[:, ["x1", "x2", "x3", "x4", "x5", "x6"]].values
y = df.loc[:, ["y"]].values

print(ruleset)

[[ 0  0  0  0  0  0]
 [ 1  0  0  0 -1  0]
 [-1  0  0  0  1  0]
 [ 1  1  0  0  0  0]
 [ 0  0  0  0 -1 -1]
 [ 0  0  0  0  1  1]
 [ 0  0  0  0 -1 -1]
 [ 0  1  0  0  0  1]
 [ 1  0  1  0  0  0]
 [ 0  0  0  1  0  1]
 [ 0  0  0  1  1  0]
 [-1  0 -1  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 0  1  0  0  1  0]
 [ 1  0  1  1  0  0]
 [ 0  0  0  1  1  1]]


## Classification algorithm - decision trees!

Lets try decision trees for our ruleset generation

In [41]:
from sklearn import tree
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(ruleset, y, test_size=0.2, random_state=42)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)



In [42]:
from itertools import combinations_with_replacement, permutations

places = 6
max_digit = 1
x_rules = []

all_combs = list(combinations_with_replacement(range(-1, max_digit+1), r=places))
for comb in sorted(all_combs, key=lambda c: c[::-1]):
    all_perms = set(permutations(comb))
    for perm in sorted(all_perms, key=lambda c: c[::-1]):
        x_rules.append(list(perm))

In [43]:
print(x_rules)
space_rules = []
y_pred_train = []
y_pred_test = []

[[-1, -1, -1, -1, -1, -1], [0, -1, -1, -1, -1, -1], [-1, 0, -1, -1, -1, -1], [-1, -1, 0, -1, -1, -1], [-1, -1, -1, 0, -1, -1], [-1, -1, -1, -1, 0, -1], [-1, -1, -1, -1, -1, 0], [0, 0, -1, -1, -1, -1], [0, -1, 0, -1, -1, -1], [-1, 0, 0, -1, -1, -1], [0, -1, -1, 0, -1, -1], [-1, 0, -1, 0, -1, -1], [-1, -1, 0, 0, -1, -1], [0, -1, -1, -1, 0, -1], [-1, 0, -1, -1, 0, -1], [-1, -1, 0, -1, 0, -1], [-1, -1, -1, 0, 0, -1], [0, -1, -1, -1, -1, 0], [-1, 0, -1, -1, -1, 0], [-1, -1, 0, -1, -1, 0], [-1, -1, -1, 0, -1, 0], [-1, -1, -1, -1, 0, 0], [0, 0, 0, -1, -1, -1], [0, 0, -1, 0, -1, -1], [0, -1, 0, 0, -1, -1], [-1, 0, 0, 0, -1, -1], [0, 0, -1, -1, 0, -1], [0, -1, 0, -1, 0, -1], [-1, 0, 0, -1, 0, -1], [0, -1, -1, 0, 0, -1], [-1, 0, -1, 0, 0, -1], [-1, -1, 0, 0, 0, -1], [0, 0, -1, -1, -1, 0], [0, -1, 0, -1, -1, 0], [-1, 0, 0, -1, -1, 0], [0, -1, -1, 0, -1, 0], [-1, 0, -1, 0, -1, 0], [-1, -1, 0, 0, -1, 0], [0, -1, -1, -1, 0, 0], [-1, 0, -1, -1, 0, 0], [-1, -1, 0, -1, 0, 0], [-1, -1, -1, 0, 0, 0], [0,

In [44]:
for vector in x_rules:
    y_pred = clf.predict([vector])
    new_list = vector + [y_pred[0]]
    # print(new_list)
    space_rules.append(new_list)

y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)
print(space_rules)

# Define the path to your existing CSV file
csv_file_path = '../sets/ruleset_result.csv'

# Convert the list of lists into a DataFrame
new_data_df = pd.DataFrame(space_rules, columns=['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'y'])

# Append the new data to the existing CSV file
new_data_df.to_csv(csv_file_path, mode='a', header=False, index=False)

[[-1, -1, -1, -1, -1, -1, -1], [0, -1, -1, -1, -1, -1, -1], [-1, 0, -1, -1, -1, -1, -1], [-1, -1, 0, -1, -1, -1, -1], [-1, -1, -1, 0, -1, -1, -1], [-1, -1, -1, -1, 0, -1, 0], [-1, -1, -1, -1, -1, 0, -1], [0, 0, -1, -1, -1, -1, -1], [0, -1, 0, -1, -1, -1, -1], [-1, 0, 0, -1, -1, -1, -1], [0, -1, -1, 0, -1, -1, -1], [-1, 0, -1, 0, -1, -1, -1], [-1, -1, 0, 0, -1, -1, -1], [0, -1, -1, -1, 0, -1, 0], [-1, 0, -1, -1, 0, -1, 0], [-1, -1, 0, -1, 0, -1, 1], [-1, -1, -1, 0, 0, -1, 0], [0, -1, -1, -1, -1, 0, -1], [-1, 0, -1, -1, -1, 0, -1], [-1, -1, 0, -1, -1, 0, -1], [-1, -1, -1, 0, -1, 0, -1], [-1, -1, -1, -1, 0, 0, 0], [0, 0, 0, -1, -1, -1, -1], [0, 0, -1, 0, -1, -1, -1], [0, -1, 0, 0, -1, -1, -1], [-1, 0, 0, 0, -1, -1, -1], [0, 0, -1, -1, 0, -1, 0], [0, -1, 0, -1, 0, -1, 0], [-1, 0, 0, -1, 0, -1, 1], [0, -1, -1, 0, 0, -1, 0], [-1, 0, -1, 0, 0, -1, 0], [-1, -1, 0, 0, 0, -1, 1], [0, 0, -1, -1, -1, 0, -1], [0, -1, 0, -1, -1, 0, -1], [-1, 0, 0, -1, -1, 0, -1], [0, -1, -1, 0, -1, 0, -1], [-1, 0, -

In [45]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Training Accuracy:", accuracy_score(y_train, y_pred_train))
print("Testing Accuracy:", accuracy_score(y_test, y_pred_test))

print("\nClassification Report:\n", classification_report(y_test, y_pred_test))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_test))

Training Accuracy: 1.0
Testing Accuracy: 0.5

Classification Report:
               precision    recall  f1-score   support

          -2       0.50      1.00      0.67         1
          -1       0.00      0.00      0.00         1
           0       1.00      1.00      1.00         1
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.30      0.40      0.33         4
weighted avg       0.38      0.50      0.42         4

Confusion Matrix:
 [[1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]]


c:\Users\vmelnyk2\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vmelnyk2\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vmelnyk2\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average

In [ ]:
moods_lower = ['angry', 'worried', 'sad', 'calm', 'happy', 'excited']
#[0,-1,0,0,1,0,2]

rules_tensor = [
    'angry high or happy low then negative',
    'angry low and happy high then positive',
    'angry medium or happy medium then neutral',
    'angry high and worried high then high_negative',
    'angry medium and worried medium then negative',
    'angry low and worried low then neutral',
    'sad high and calm low then high_negative',
    'sad medium and calm medium then neutral',
    'sad low and calm high then positive',
    'happy high and excited high then high_positive',
    'happy medium and excited medium then neutral',
    'happy low and excited low then negative',
    'angry high and happy low then negative',
    'angry low and happy high then positive',
    'worried high and excited high then neutral',
    'worried low and excited low then neutral',
    'sad high and excited low then negative',
    'sad low and excited low then positive',
    'angry high and calm high then neutral',
    'angry high and calm low then high_negative',
    'angry low and calm high then high_positive',
    'worried high and happy high then neutral',
    'worried high and happy low then negative',
    'worried low and happy high then high_positive',
    'sad high and excited high then neutral',
    'sad high and excited low then negative',
    'sad low and excited high then high_positive',
    'calm high and excited high then positive',
    'calm high and excited low then positive',
    'calm low and excited high then positive',
    'angry high and sad high then high_negative',
    'angry low and sad low then neutral',
    'angry high and sad low then negative',
    'happy high and worried high then neutral',
    'happy high and worried low then high_positive',
    'happy low and worried high then negative',
    'happy high and calm high then high_positive',
    'happy medium and calm medium then positive',
    'calm medium and excited medium then positive'
    ]