In [2]:
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
from skfuzzy import control as ctrl
import pandas as pd

# Automated rule generation

The basic idea here is to introduce the automated rule generation for fuzzy logic ruleset.

In [3]:
moods = ["Angry", "Worried", "Sad", "Calm", "Happy", "Excited"]

df = pd.read_csv('../sets/ruleset_train.csv')
ruleset_train = df.loc[:, ["x1", "x2", "x3", "x4", "x5", "x6"]].values
y_train = df.loc[:, ["y"]].values

print(ruleset_train)

[[ 0  0  0  0  0  0]
 [ 1  0  0  0 -1  0]
 [-1  0  0  0  1  0]
 [ 1  1  0  0  0  0]
 [ 0  0  0  0 -1 -1]
 [ 0  0  0  0  1  1]
 [ 0  0  0  0 -1 -1]
 [ 0  1  0  0  0  1]
 [ 1  0  1  0  0  0]
 [ 0  0  0  1  0  1]
 [ 0  0  0  1  1  0]
 [-1  0 -1  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 0  1  0  0  1  0]
 [ 1  0  1  1  0  0]
 [ 0  0  0  1  1  1]]


## Classification algorithm - decision trees!

Lets try decision trees for our ruleset generation

In [6]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(ruleset_train, y_train)

