# This is a sandbox

In [6]:
# imports section
import numpy as np
import math
from numpy import dot
from numpy.linalg import norm
from gensim import corpora, models, similarities
import string

import gensim.downloader as api
from gensim.models import Word2Vec

In [ ]:
text = "text text text Valentyn hello"

In [2]:
def tokenize(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))

    # ADD MORE PROCESSING

    corpus = text.split(' ')
    return corpus

print(tokenize("hello. how are you! yeah&"))

['hello', 'how', 'are', 'you', 'yeah']


In [4]:
def tfidf_example(texts):
    corpuses = [tokenize(text) for text in texts]

    vocab = sorted(set(sum(corpuses, [])))
    vocab_dict = {k:i for i,k in enumerate(vocab)}

    X_tf = np.zeros((len(corpuses), len(vocab)), dtype=int)

    for i, doc in enumerate(corpuses): # try with pandas
        for word in doc:
            X_tf[i, vocab_dict[word]] += 1

    print(X_tf.astype(bool).sum(axis=0))
    idf = np.log(X_tf.shape[0]/X_tf.astype(bool).sum(axis=0))
    X_tfidf = X_tf * idf

    X_tfidf_norm = X_tfidf / np.linalg.norm(X_tfidf, axis=1)[:,None]
    M = X_tfidf_norm @ X_tfidf_norm.T # pytorch 
    print(M)

    return 

texts = ["text text text Valentyn hello", "hello hello", "Valentyn Nastya hello", "test qwerty", "test qwerty"]
texts_new = ["Oleksandr likes to walk with his dog", "Oleksandr and his dog are best friends", "hello world this is dummy text"]
tfidf_example(texts_new)

[1 1 1 2 1 1 1 2 1 1 2 1 1 1 1 1 1]
[[1.         0.09269042 0.        ]
 [0.09269042 1.         0.        ]
 [0.         0.         1.        ]]


1. word2vec
2. datasets parsing
3. ml algorithms 
4. ml + fl 
5. pandas, pytorch 
6. entropy - where it marks wrong point
7. 

In [7]:
corpus = api.load('glove-wiki-gigaword-100')

vector = corpus['computer']
print(vector)


[-1.6298e-01  3.0141e-01  5.7978e-01  6.6548e-02  4.5835e-01 -1.5329e-01
  4.3258e-01 -8.9215e-01  5.7747e-01  3.6375e-01  5.6524e-01 -5.6281e-01
  3.5659e-01 -3.6096e-01 -9.9662e-02  5.2753e-01  3.8839e-01  9.6185e-01
  1.8841e-01  3.0741e-01 -8.7842e-01 -3.2442e-01  1.1202e+00  7.5126e-02
  4.2661e-01 -6.0651e-01 -1.3893e-01  4.7862e-02 -4.5158e-01  9.3723e-02
  1.7463e-01  1.0962e+00 -1.0044e+00  6.3889e-02  3.8002e-01  2.1109e-01
 -6.6247e-01 -4.0736e-01  8.9442e-01 -6.0974e-01 -1.8577e-01 -1.9913e-01
 -6.9226e-01 -3.1806e-01 -7.8565e-01  2.3831e-01  1.2992e-01  8.7721e-02
  4.3205e-01 -2.2662e-01  3.1549e-01 -3.1748e-01 -2.4632e-03  1.6615e-01
  4.2358e-01 -1.8087e+00 -3.6699e-01  2.3949e-01  2.5458e+00  3.6111e-01
  3.9486e-02  4.8607e-01 -3.6974e-01  5.7282e-02 -4.9317e-01  2.2765e-01
  7.9966e-01  2.1428e-01  6.9811e-01  1.1262e+00 -1.3526e-01  7.1972e-01
 -9.9605e-04 -2.6842e-01 -8.3038e-01  2.1780e-01  3.4355e-01  3.7731e-01
 -4.0251e-01  3.3124e-01  1.2576e+00 -2.7196e-01 -8

In [10]:
print(corpus.similarity('woman', 'man'), '\n')

print(corpus.similarity('sandwich', 'man'), '\n')
print(corpus.distance("media", "media"), '\n')

0.8323495 

0.2676646 

5.960464477539063e-08 



In [3]:
def tfidf_wordvec(texts):
    model = Word2Vec(corpus, vector_size=len(texts), min_count=1)
    return 0

arr = [np.array(corpus['fascism']),
       np.array(corpus['hitler']),
       np.array(corpus['italy']),
       np.array(corpus['mussolini'])]

new_vector = arr[1] + arr[2]
new_vector_normalized = new_vector / np.linalg.norm(new_vector)
mussolini = arr[3] / np.linalg.norm(arr[3])
cosine_sim = new_vector_normalized @ mussolini.T

print(cosine_sim)

print(corpus['democracy'])

# print(corpus.similarity('woman', 'man'), '\n')
# print(corpus.similarity('fascism', 'mussolini'), '\n')
# print(corpus.similarity('fascism', 'trump'), '\n')
# print(corpus.distance("media", "media"), '\n')

0.711108
[-0.215     0.87737  -0.063965 -0.042852  0.86186   0.89338  -0.35324
 -0.99678   0.15289   0.066144 -0.52534   0.68397   0.34208  -0.1562
 -0.73768   0.20957   0.16697  -0.039477 -0.43481  -0.24743   0.43591
 -0.058181  0.65537  -0.28042   0.37273   0.36553   0.1083   -0.67762
  0.57978   0.38404   0.31276   1.0281    0.12181   0.47344   0.43453
 -0.5851    0.30595   0.43365  -1.0241   -0.72537  -1.7373   -0.65151
  0.80613  -0.15615  -0.27365  -1.0545    0.52086   0.15272  -0.60403
 -0.33367  -0.17697  -0.2755   -0.42711   1.3151    0.37881  -1.2953
  0.18912   0.41696   1.4792   -0.0141   -1.1892   -0.30676  -1.311
 -0.70105   0.67542   0.58331  -0.35846  -0.4816    0.31092  -0.065241
  1.3389    0.16039  -0.88174  -0.57881   0.21681  -0.17917  -0.10835
  0.25223  -0.9224   -0.28561   0.52446   0.40163   0.22797   0.68122
 -0.71693   1.2085    0.26086   0.30124   0.17424  -0.82416   0.96425
 -0.44436  -0.14183   0.84599  -0.59692  -0.42527   0.52494  -0.78475
  0.31882   0.

In [35]:
x_train = np.array( [corpus['democracy'], corpus['election'], corpus['public'], corpus['economy'], corpus['capitalism'], 
corpus['fascism'], corpus['eagle'], corpus['hitler'], corpus['mussolini'], corpus['freedom'], 
corpus['stalin'], corpus['gulag'], corpus['collectivism']])

y_train = np.array([[0.1, 1.0, 0.9, 0.0], [0.2, 0.9, 0.8, 0.0], [0.8, 0.8, 0.5, 0.3], [0.1, 0.7, 0.9, 0.5], [0.1, 0.8, 0.9, 0.5],
                    [0.2, 0.3, 0.4, 0.9], [0.1, 0.6, 0.2, 0.6], [0.1, 0.2, 0.1, 0.9], [0.1, 0.2, 0.1, 0.9], [0.1, 0.9, 0.9, 0.1], 
                    [0.9, 0.2, 0.1, 0.1], [0.9, 0.1, 0.1, 0.1], [0.9, 0.3, 0.3, 0.6]])

def add_property(x, y, property, vector):
    x = np.append(x, [corpus[property]], axis=0)
    y = np.append(y, [vector], axis=0)
    return x, y

x_train, y_train = add_property(x_train, y_train, 'culture', [0.8, 0.8, 0.5, 0.1])
x_train, y_train = add_property(x_train, y_train, 'society', [0.8, 0.8, 0.4, 0.1])
x_train, y_train = add_property(x_train, y_train, 'trump', [0.1, 0.2, 0.6, 0.6])
x_train, y_train = add_property(x_train, y_train, 'biden', [0.1, 0.7, 0.4, 0.4])
x_train, y_train = add_property(x_train, y_train, 'obama', [0.1, 0.7, 0.4, 0.2])
x_train, y_train = add_property(x_train, y_train, 'clinton', [0.1, 0.7, 0.4, 0.4])
x_train, y_train = add_property(x_train, y_train, 'satana', [0.9, 0.9, 0.9, 0.9])
x_train, y_train = add_property(x_train, y_train, 'jesus', [0.9, 0.9, 0.9, 0.1])
x_train, y_train = add_property(x_train, y_train, 'dictatorship', [0.9, 0.1, 0.1, 0.9])
x_train, y_train = add_property(x_train, y_train, 'socialism', [0.9, 0.1, 0.1, 0.3])

# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])
# x_train, y_train = add_property(x_train, y_train, 'party', [0.9, 0.5, 0.4, 0.4])


In [25]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

# Define the degree of the polynomial features
degree = 3  # You can experiment with different degrees

# Create a pipeline that includes PolynomialFeatures and LinearRegression
model = Pipeline([
    ('poly', PolynomialFeatures(degree=degree)),
    ('linear', LinearRegression())
])

# Train the model
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict([corpus["labour"]])
print(y_pred)

[[0.56809288 0.75469388 0.71935965 0.51559354]]


In [38]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

# Create a RandomForestRegressor wrapped in MultiOutputRegressor for multi-dimensional output
model = MultiOutputRegressor(RandomForestRegressor(n_estimators=100, random_state=42))

# Train the model
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict([corpus["lenin"]])
print(y_pred)

[[0.582 0.451 0.316 0.515]]


In [36]:
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# Create a pipeline with StandardScaler and SVR, wrapped in MultiOutputRegressor
model = MultiOutputRegressor(make_pipeline(StandardScaler(), SVR(kernel='rbf', C=1.0, epsilon=0.1)))

# Train the model
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict([corpus["lenin"]])
print(y_pred)

[[0.65840325 0.43756947 0.37288896 0.29836469]]


In [ ]:
def multiply_vectors(x, y):
    return 0